config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  resources :word_set
end

app/models/word_set.rb
class WordSet < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @word_sets = WordSet.all
  end
end

app/controllers/word_set_controller.rb
class WordSetController < ApplicationController
  def show
  end

  def update
    word_set = WordSet.find(params[:id])
    word_set.update(word_params)
    redirect_to pirate_path
  end

  private

  def word_params
    params.require(:word_set).permit(:noun1, :adjective1, :verb1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/word_set_helper.rb
module WordSetHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hashlibs</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Metamorphous' rel='stylesheet' type='text/css'>  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<ul>
  <% @word_sets.each do |word_set| %>
    <li>
      <%= link_to word_set.name, word_set_path(id: word_set.id) %>
    </li>
  <% end %>
</ul>

app/views/word_set/show.html.erb
<h1 class="text-center">How to Talk Like a Pirate</h1>
<p id="story" class="text-left">Create values for the hashes below:</p>

<div class="row">
<div id="story-form">
  <%= form_for :word_set, method: "put" do |f| %>
    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun1] =</span>
             <%= f.text_field :noun1, id: "formnoun1", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:adjective1] =</span>
          <%= f.text_field :adjective1, id: "formadjective1", class: "form-control", placeholder: "adjective" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:verb1] =</span>
          <%= f.text_field :verb1, id: "formverb1", class: "form-control", placeholder: "verb" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:adverb1] =</span>
          <%= f.text_field :adverb1, id: "formadverb1", class: "form-control", placeholder: "adverb" %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun2] =</span>
          <%= f.text_field :noun2, id: "formnoun2", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:adjective2] =</span>
          <%= f.text_field :adjective2, id: "formadjective2", class: "form-control", placeholder: "adjective" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:plural_noun1] =</span>
          <%= f.text_field :plural_noun1, id: "formpluralnoun1", class: "form-control", placeholder: "plural noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:plural_noun2] =</span>
          <%= f.text_field :plural_noun2, id: "formpluralnoun2", class: "form-control", placeholder: "plural noun" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:plural_noun3] =</span>
          <%= f.text_field :plural_noun3, id: "formpluralnoun3", class: "form-control", placeholder: "plural noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun3] =</span>
          <%= f.text_field :noun3, id: "formnoun3", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun4] =</span>
          <%= f.text_field :noun4, id: "formnoun4", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun5] =</span>
          <%= f.text_field :noun5, id: "formnoun5", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:noun6] =</span>
          <%= f.text_field :noun6, id: "formnoun6", class: "form-control", placeholder: "noun" %>
        </div>
      </div>
      <div class="col-xs-6">
        <div class="input-group">
          <span class="input-group-addon">word_set[:part_of_the_body1] =</span>
          <%= f.text_field :part_of_the_body2, id: "formbodypart1", class: "form-control", placeholder: "body part" %>
        </div>
      </div>
    </div>
    <% end %>
</div>

<p id="story">
Ye can always pretend to be a bloodthirsty <span id="noun1" class="word-holder"></span>, threatening everyone by
waving yer <span id="adjective1" class="word-holder"></span> sword in the air, but until ye learn to <span id="verb1" class="word-holder"></span> like a
pirate, ye’ll never be <span id="adverb1" class="word-holder"></span> accepted as an authentic <span id="noun2" class="word-holder"></span>. So here’s what
ye do: Cleverly work into yer daily conversations <span id="adjective2" class="word-holder"></span> pirate phrases
such as “Ahoy there, <span id="plural_noun1"  class="word-holder"></span>,” “avast, ye <span id="plural_noun2" class="word-holder"></span>”, and “Shiver me
<span id="plural_noun3" class="word-holder"></span>”. Remember to drop all yer gs when ye say such words as sailin’,
spittin’,  and fightin’. Once ye have the lingo down pat, it helps to wear a
three-cornered <span id="noun3" class="word-holder"></span> on yer head, stash a/an <span id="noun4" class="word-holder"></span> in yer pants, and keep a/an
<span id="noun5" class="word-holder"></span> perched atop yer <span id="bodypart1" class="word-holder"></span>. Aye, now ye be a real pirate!
</p>
</div> <!-- end top ros -->